### ISSUE TITLE
[Ruby] Support newer releases of the FFI gem

### ISSUE THREAD

**Issue by Th3-M4jor** [Unleash/yggdrasil#150]
### Describe the feature request

Can the Ruby bindings be made to work with newer releases of the ffi gem? Its preventing us from upgrading the unleash ruby client to `6.0` due to dependency conflicts.

### Background

The unleash ruby client version `6.0.5` depends on `yggdrasil-engine ~> 0.0.6` which depends on `ffi ~> 1.15.5` and we depend on `ffi ~> 1.16.3`

### Solution suggestions

While I haven't dug into the Ruby bindings to see if there's a reason for not allowing newer versions of the ffi gem, it should be as simple as changing which versions of the ffi gem are allowed.

**Comment by sighphyre** [comment]
Hey @Th3-M4jor, thanks for reporting this. There shouldn't be any reason why we can't upgrade, I'll try patch that today

**Comment by sighphyre** [comment]
@Th3-M4jor, we've upgraded and released, you should be able to pick up the latest Unleash ruby client. Thanks again for reporting this!
