### ISSUE TITLE
Provide 32-bit native binary

### ISSUE THREAD

**Issue by Pilzinsel64** [Unleash/yggdrasil#177]
### Describe the feature request

You're providing 64-bit binary binary. Please also provide a 32-bit binary if possible.
Alternative: Distribute 64-bit libraries also for 32-bit in the `Unleash.Yggdrasil` nuget package.

### Background

We distribute our applicaitons with win-x86 .NET runtime for several performance and compatibility reasons. However, updating our projects to use Unleash.Client v5.0.0 nuget packages leads to the result that after publishing as win-x86 applicaiton that the native DLL `yggdrasilffi` can not be found. .NET don't copy it to the output when publishing as win-x86 application as it's only available for win-x64 and not for win-x86.
![grafik](https://github.com/user-attachments/assets/8e2867e9-4cd7-4cad-9281-746555371a06)
![grafik](https://github.com/user-attachments/assets/c72e47fd-76cf-416a-afbc-d4576e51ce97)

```
System.DllNotFoundException: Unable to load DLL 'yggdrasilffi' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)    at Yggdrasil.FFI.new_engine()
   at Yggdrasil.FFI.NewEngine()
   at Yggdrasil.YggdrasilEngine..ctor(List`1 strategies)
   at Unleash.UnleashServices..ctor(UnleashSettings settings, EventCallbackConfig eventConfig, List`1 strategies)
   at Unleash.DefaultUnleash..ctor(UnleashSettings settings, IStrategy[] strategies)
```

Without win-x86 native libraries we would need to stick to the old version, continue maintenance by making a fork of it, or need to switch to win-x64 just for the unleash client.

**Comment by sighphyre** [comment]
Hey @Pilzinsel64, that shouldn't be a problem. Build is already published, I just need to go through the dance of getting a virtual machine setup to test this

**Comment by Pilzinsel64** [comment]
Thank you very much! It works fine now.

**Comment by sighphyre** [comment]
Nothing but a pleasure! Thanks for the report!
